"""
strategies/base.py - Abstract Base Class for All Raidillon Strategies

This module defines the Strategy interface that all concrete strategies must implement.
It provides the foundational contract for entry signals, exit signals, position sizing,
and lifecycle management throughout the backtest.

Design Philosophy:
-----------------
1. Strategies are stateless evaluators - they don't track positions themselves
2. The backtest engine owns position state and calls strategies for signals
3. Strategies return Signal objects that the engine interprets into actions
4. Each strategy maps 1:1 with a definition in strategies.yaml

The flow is:
    Engine.step() -> Strategy.check_entry() -> Signal or None
                  -> Strategy.check_exit(position) -> Signal or None
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, date, timedelta
from typing import Optional, Dict, List, Any, Union, Tuple
from enum import Enum
import logging

logger = logging.getLogger('raidillon.strategies')


class SignalType(Enum):
    """Type of trading signal generated by a strategy."""
    ENTRY = "ENTRY"           # Open a new position
    EXIT_FULL = "EXIT_FULL"   # Close entire position
    EXIT_PARTIAL = "EXIT_PARTIAL"  # Close part of position
    SCALE_IN = "SCALE_IN"     # Add to existing position
    ROLL = "ROLL"             # Roll to new expiration
    NO_ACTION = "NO_ACTION"   # Explicitly no action


class ExitReason(Enum):
    """Reason for exiting a position - used for attribution and analysis."""
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    TIME_STOP = "TIME_STOP"
    THESIS_INVALIDATION = "THESIS_INVALIDATION"
    KILL_SWITCH = "KILL_SWITCH"
    EXPIRATION = "EXPIRATION"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    MANUAL = "MANUAL"
    PAIRS_EXIT = "PAIRS_EXIT"


@dataclass
class Signal:
    """
    A trading signal generated by a strategy.
    
    Signals are the primary communication mechanism between strategies and the
    backtest engine. A Signal describes WHAT to do, and the engine figures out
    HOW to do it (position sizing, order management, etc.).
    
    Attributes:
        signal_type: Type of signal (ENTRY, EXIT_FULL, etc.)
        strategy_name: Name of the strategy generating this signal
        underlying: Ticker symbol for the trade
        timestamp: When the signal was generated
        target_structure: Dict describing the position structure (for entries)
        exit_reason: Why we're exiting (for exits)
        urgency: 1-5 scale, 5 being most urgent (affects execution priority)
        notes: Additional context for logging/analysis
        confidence: 0-1 confidence score (optional, for ML strategies)
    """
    signal_type: SignalType
    strategy_name: str
    underlying: str
    timestamp: datetime
    target_structure: Optional[Dict[str, Any]] = None
    exit_reason: Optional[ExitReason] = None
    exit_pct: float = 1.0  # For partial exits, what percentage to close
    urgency: int = 3  # 1=low, 5=critical
    notes: str = ""
    confidence: Optional[float] = None
    
    def __post_init__(self):
        """Validate signal consistency."""
        if self.signal_type == SignalType.ENTRY and self.target_structure is None:
            raise ValueError("ENTRY signals must include target_structure")
        if self.signal_type in (SignalType.EXIT_FULL, SignalType.EXIT_PARTIAL) and self.exit_reason is None:
            raise ValueError("EXIT signals must include exit_reason")
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize signal for logging."""
        return {
            'signal_type': self.signal_type.value,
            'strategy_name': self.strategy_name,
            'underlying': self.underlying,
            'timestamp': self.timestamp.isoformat(),
            'exit_reason': self.exit_reason.value if self.exit_reason else None,
            'exit_pct': self.exit_pct,
            'urgency': self.urgency,
            'notes': self.notes,
        }


@dataclass
class StrategyConfig:
    """
    Configuration for a strategy, parsed from strategies.yaml.
    
    This dataclass standardizes the configuration interface so strategies
    don't need to parse raw YAML dictionaries themselves.
    """
    name: str
    enabled: bool
    tier: str  # A, B, HEDGE
    conviction_score: Optional[int]
    theme: str
    underlying: str
    structure_type: str  # debit_call_spread, debit_put_spread, long_put, etc.
    
    # Leg definitions
    long_strike: Optional[float] = None
    short_strike: Optional[float] = None
    expiration_target_dte: int = 30
    right: str = "C"  # C or P
    
    # Entry window
    entry_start: Optional[date] = None
    entry_end: Optional[date] = None
    
    # Entry conditions (list of condition dicts)
    entry_conditions: List[Dict[str, Any]] = field(default_factory=list)
    
    # Exit rules
    exit_rules: Dict[str, Any] = field(default_factory=dict)
    
    # Catalysts
    catalysts: List[Dict[str, Any]] = field(default_factory=list)
    
    # Position sizing by variant
    sizing_conservative: float = 0
    sizing_base: float = 0
    sizing_aggressive: float = 0
    
    # Verification gates (for contingent strategies like MPC)
    verification_gate: Optional[Dict[str, Any]] = None
    
    # Raw config for anything else
    raw_config: Dict[str, Any] = field(default_factory=dict)
    
    @classmethod
    def from_yaml(cls, name: str, config_dict: Dict[str, Any]) -> 'StrategyConfig':
        """
        Factory method to create StrategyConfig from parsed YAML.
        
        Args:
            name: Strategy name (e.g., 'VLO_EARNINGS_CALL_SPREAD')
            config_dict: The strategy section from strategies.yaml
            
        Returns:
            Populated StrategyConfig instance
        """
        # Extract structure details
        structure = config_dict.get('structure', {})
        legs = structure.get('legs', {})
        
        # Determine strikes - check for override first, then leg definitions
        strike_override = config_dict.get('strike_override', {})
        long_strike = strike_override.get('long_strike')
        short_strike = strike_override.get('short_strike')
        
        if long_strike is None and 'long' in legs:
            long_leg = legs['long']
            if long_leg.get('strike_selection') == 'fixed':
                long_strike = long_leg.get('strike_value')
        
        if short_strike is None and 'short' in legs:
            short_leg = legs['short']
            if short_leg.get('strike_selection') == 'fixed':
                short_strike = short_leg.get('strike_value')
        
        # Determine right (call or put) from leg definitions
        right = 'C'  # default
        if 'long' in legs:
            right = legs['long'].get('right', 'C')
        
        # Parse entry window dates
        entry_window = config_dict.get('entry_window', {})
        entry_start = None
        entry_end = None
        if entry_window.get('start'):
            entry_start = datetime.strptime(entry_window['start'], '%Y-%m-%d').date()
        if entry_window.get('end'):
            entry_end = datetime.strptime(entry_window['end'], '%Y-%m-%d').date()
        
        # Extract sizing
        sizing = config_dict.get('position_sizing', {})
        
        return cls(
            name=name,
            enabled=config_dict.get('enabled', True),
            tier=config_dict.get('tier', 'B'),
            conviction_score=config_dict.get('conviction_score'),
            theme=config_dict.get('theme', 'unknown'),
            underlying=config_dict.get('underlying', ''),
            structure_type=structure.get('type', 'unknown'),
            long_strike=long_strike,
            short_strike=short_strike,
            expiration_target_dte=structure.get('expiration_target_dte', 30),
            right=right,
            entry_start=entry_start,
            entry_end=entry_end,
            entry_conditions=config_dict.get('entry_conditions', []),
            exit_rules=config_dict.get('exit_rules', {}),
            catalysts=config_dict.get('catalysts', []),
            sizing_conservative=sizing.get('conservative', 0),
            sizing_base=sizing.get('base', 0),
            sizing_aggressive=sizing.get('aggressive', 0),
            verification_gate=config_dict.get('verification_gate'),
            raw_config=config_dict,
        )
    
    def get_sizing(self, variant: str) -> float:
        """Get position size for a specific portfolio variant."""
        sizing_map = {
            'conservative': self.sizing_conservative,
            'base': self.sizing_base,
            'aggressive': self.sizing_aggressive,
        }
        return sizing_map.get(variant, self.sizing_base)
    
    def get_primary_catalyst(self) -> Optional[Dict[str, Any]]:
        """Get the first/primary catalyst for this strategy."""
        if self.catalysts:
            return self.catalysts[0]
        return None


@dataclass
class MarketSnapshot:
    """
    A point-in-time snapshot of all market data needed for strategy evaluation.
    
    The backtest engine creates these snapshots and passes them to strategies.
    This ensures strategies can't accidentally look into the future.
    
    Attributes:
        timestamp: The current simulation time
        prices: Dict of ticker -> price (most recent close or current)
        vix_spot: Current VIX index level
        vix_futures: Dict of tenor -> price (M1, M2, etc.)
        rates: Dict of tenor -> rate (3M, 2Y, 10Y, etc.)
        crack_spreads: Dict of region -> spread (USGC, etc.)
        cftc_positioning: Net speculative position in VIX futures
        options_chains: Dict of underlying -> chain DataFrame
        calendar_events: Events happening on this date
        iv_data: Dict of underlying -> IV rank/percentile
    """
    timestamp: datetime
    prices: Dict[str, float] = field(default_factory=dict)
    vix_spot: Optional[float] = None
    vix_futures: Dict[str, float] = field(default_factory=dict)
    rates: Dict[str, float] = field(default_factory=dict)
    crack_spreads: Dict[str, float] = field(default_factory=dict)
    cftc_positioning: Optional[int] = None
    options_chains: Dict[str, Any] = field(default_factory=dict)
    calendar_events: List[Dict[str, Any]] = field(default_factory=list)
    iv_data: Dict[str, Dict[str, float]] = field(default_factory=dict)
    
    # Lookback data for condition evaluation
    price_history: Dict[str, List[Tuple[date, float]]] = field(default_factory=dict)
    earnings_results: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    
    def get_price(self, ticker: str) -> Optional[float]:
        """Get price for a ticker, returns None if not available."""
        return self.prices.get(ticker.upper())
    
    def get_iv_rank(self, ticker: str) -> Optional[float]:
        """Get IV rank (0-100) for a ticker."""
        iv_info = self.iv_data.get(ticker.upper(), {})
        return iv_info.get('iv_rank')
    
    def days_until_event(self, event_type: str, ticker: Optional[str] = None) -> Optional[int]:
        """
        Calculate days until a specific event type.
        
        Args:
            event_type: Type of event (EARNINGS, FOMC, etc.)
            ticker: Optional ticker filter (for EARNINGS)
            
        Returns:
            Number of days until event, or None if no matching event found
        """
        current_date = self.timestamp.date() if isinstance(self.timestamp, datetime) else self.timestamp
        
        for event in self.calendar_events:
            if event.get('event_type') != event_type:
                continue
            if ticker and event.get('ticker', '').upper() != ticker.upper():
                continue
            
            event_date = event.get('event_date')
            if event_date:
                if isinstance(event_date, str):
                    event_date = datetime.strptime(event_date, '%Y-%m-%d').date()
                elif isinstance(event_date, datetime):
                    event_date = event_date.date()
                
                if event_date >= current_date:
                    return (event_date - current_date).days
        
        return None
    
    def has_event_today(self, event_type: str, ticker: Optional[str] = None) -> bool:
        """Check if a specific event type occurs today."""
        days = self.days_until_event(event_type, ticker)
        return days == 0 if days is not None else False


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Concrete strategies must implement:
    - check_entry(): Evaluate entry conditions and return Signal or None
    - check_exit(): Evaluate exit conditions for open positions
    - get_target_structure(): Define the option structure to trade
    
    Strategies should NOT:
    - Track position state (that's the engine's job)
    - Execute trades (that's the engine's job)
    - Access data outside the MarketSnapshot (prevents lookahead bias)
    """
    
    def __init__(self, config: StrategyConfig):
        """
        Initialize strategy with configuration.
        
        Args:
            config: StrategyConfig parsed from strategies.yaml
        """
        self.config = config
        self.name = config.name
        self.logger = logging.getLogger(f'raidillon.strategy.{self.name}')
        
        # Track whether we've generated an entry signal (for one-time entries)
        self._entry_signal_generated = False
        
    @abstractmethod
    def check_entry(self, snapshot: MarketSnapshot) -> Optional[Signal]:
        """
        Evaluate whether to enter a new position.
        
        This method is called by the engine on every bar when we don't have
        an open position for this strategy. It should:
        1. Check if we're in the entry window
        2. Evaluate all entry conditions
        3. Return a Signal if conditions are met, None otherwise
        
        Args:
            snapshot: Current market state
            
        Returns:
            Signal with type ENTRY if conditions met, None otherwise
        """
        pass
    
    @abstractmethod
    def check_exit(
        self, 
        snapshot: MarketSnapshot, 
        position: Any,
        position_pnl_pct: float
    ) -> Optional[Signal]:
        """
        Evaluate whether to exit an open position.
        
        This method is called by the engine on every bar when we have an
        open position for this strategy. It should:
        1. Check take-profit conditions
        2. Check stop-loss conditions
        3. Check time stops
        4. Check thesis invalidation conditions
        
        Args:
            snapshot: Current market state
            position: The open Position object
            position_pnl_pct: Current P&L as percentage of max loss
            
        Returns:
            Signal with type EXIT_* if should exit, None otherwise
        """
        pass
    
    @abstractmethod
    def get_target_structure(self, snapshot: MarketSnapshot) -> Dict[str, Any]:
        """
        Define the target option structure for this strategy.
        
        Called by the engine when processing an ENTRY signal to determine
        what position to open. Returns a dict that the engine uses to
        construct a Position object.
        
        Args:
            snapshot: Current market state (for ATM strike calculation, etc.)
            
        Returns:
            Dict with keys: structure_type, underlying, expiration, 
            long_strike, short_strike (if spread), right, etc.
        """
        pass
    
    def is_in_entry_window(self, current_date: date) -> bool:
        """Check if current date is within the entry window."""
        if self.config.entry_start and current_date < self.config.entry_start:
            return False
        if self.config.entry_end and current_date > self.config.entry_end:
            return False
        return True
    
    def reset(self):
        """Reset strategy state for a new backtest run."""
        self._entry_signal_generated = False
    
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}({self.name})>"


class VerticalSpreadStrategy(BaseStrategy):
    """
    Concrete strategy implementation for vertical spreads (call or put).
    
    This handles:
    - Debit call spreads (bullish)
    - Debit put spreads (bearish)
    - Credit spreads (if needed)
    
    Most of the strategies in strategies.yaml are vertical spreads, so this
    class handles the common logic and can be parameterized via config.
    """
    
    def check_entry(self, snapshot: MarketSnapshot) -> Optional[Signal]:
        """Evaluate entry conditions for a vertical spread."""
        
        # Don't re-enter if we've already generated an entry signal
        if self._entry_signal_generated:
            return None
        
        # Check if strategy is enabled
        if not self.config.enabled:
            return None
        
        # Check entry window
        current_date = snapshot.timestamp.date() if isinstance(snapshot.timestamp, datetime) else snapshot.timestamp
        if not self.is_in_entry_window(current_date):
            return None
        
        # Evaluate entry conditions
        conditions_met, failed_condition = self._evaluate_entry_conditions(snapshot)
        
        if not conditions_met:
            self.logger.debug(f"Entry conditions not met: {failed_condition}")
            return None
        
        # All conditions met - generate entry signal
        self._entry_signal_generated = True
        
        structure = self.get_target_structure(snapshot)
        
        return Signal(
            signal_type=SignalType.ENTRY,
            strategy_name=self.name,
            underlying=self.config.underlying,
            timestamp=snapshot.timestamp,
            target_structure=structure,
            urgency=4 if self.config.tier == 'A' else 3,
            notes=f"Entry conditions met for {self.name}",
            confidence=self.config.conviction_score / 100 if self.config.conviction_score else None,
        )
    
    def check_exit(
        self, 
        snapshot: MarketSnapshot, 
        position: Any,
        position_pnl_pct: float
    ) -> Optional[Signal]:
        """Evaluate exit conditions for an open vertical spread."""
        
        current_date = snapshot.timestamp.date() if isinstance(snapshot.timestamp, datetime) else snapshot.timestamp
        underlying_price = snapshot.get_price(self.config.underlying)
        
        exit_rules = self.config.exit_rules
        
        # 1. Check take-profit
        tp_rules = exit_rules.get('take_profit', {})
        if tp_rules:
            tp_signal = self._check_take_profit(snapshot, underlying_price, position_pnl_pct, tp_rules)
            if tp_signal:
                return tp_signal
        
        # 2. Check stop-loss
        sl_rules = exit_rules.get('stop_loss', {})
        if sl_rules:
            sl_signal = self._check_stop_loss(snapshot, underlying_price, position_pnl_pct, sl_rules)
            if sl_signal:
                return sl_signal
        
        # 3. Check time stop
        time_stop = exit_rules.get('time_stop', {})
        if time_stop:
            ts_signal = self._check_time_stop(current_date, time_stop)
            if ts_signal:
                return ts_signal
        
        # 4. Check thesis invalidation
        invalidations = exit_rules.get('thesis_invalidation', [])
        if invalidations:
            inv_signal = self._check_thesis_invalidation(snapshot, invalidations)
            if inv_signal:
                return inv_signal
        
        # 5. Check kill switch (specific to VIX strategy)
        kill_switch = exit_rules.get('kill_switch', {})
        if kill_switch:
            ks_signal = self._check_kill_switch(snapshot, kill_switch)
            if ks_signal:
                return ks_signal
        
        return None
    
    def get_target_structure(self, snapshot: MarketSnapshot) -> Dict[str, Any]:
        """Build the target spread structure."""
        
        # Calculate expiration date based on DTE target
        current_date = snapshot.timestamp.date() if isinstance(snapshot.timestamp, datetime) else snapshot.timestamp
        target_expiration = current_date + timedelta(days=self.config.expiration_target_dte)
        
        # Adjust to next Friday (standard option expiration)
        days_until_friday = (4 - target_expiration.weekday()) % 7
        if days_until_friday == 0 and target_expiration.weekday() != 4:
            days_until_friday = 7
        target_expiration = target_expiration + timedelta(days=days_until_friday)
        
        # Get strikes - use fixed strikes from config or calculate from ATM
        long_strike = self.config.long_strike
        short_strike = self.config.short_strike
        
        if long_strike is None or short_strike is None:
            # Calculate ATM-based strikes
            underlying_price = snapshot.get_price(self.config.underlying)
            if underlying_price:
                # Round to nearest standard strike
                atm_strike = round(underlying_price / 5) * 5
                
                # Use structure definition for offsets
                legs = self.config.raw_config.get('structure', {}).get('legs', {})
                long_offset = legs.get('long', {}).get('strike_offset', 0)
                short_offset = legs.get('short', {}).get('strike_offset', 0)
                
                long_strike = atm_strike + long_offset
                short_strike = atm_strike + short_offset
        
        return {
            'structure_type': self.config.structure_type,
            'underlying': self.config.underlying,
            'expiration': target_expiration,
            'long_strike': long_strike,
            'short_strike': short_strike,
            'right': self.config.right,
            'quantity': 1,  # Engine will adjust based on sizing
        }
    
    def _evaluate_entry_conditions(self, snapshot: MarketSnapshot) -> Tuple[bool, Optional[str]]:
        """
        Evaluate all entry conditions.
        
        Returns:
            Tuple of (all_conditions_met, failed_condition_name)
        """
        for condition in self.config.entry_conditions:
            condition_type = condition.get('condition', '')
            
            # VIX spot level condition
            if condition_type == 'vix_spot_below':
                threshold = condition.get('threshold', 20)
                if snapshot.vix_spot and snapshot.vix_spot >= threshold:
                    return False, f"VIX spot {snapshot.vix_spot:.2f} >= {threshold}"
            
            # CFTC net short position
            elif condition_type == 'cftc_net_short_above':
                threshold = condition.get('threshold', 50000)
                if snapshot.cftc_positioning is None:
                    continue  # Skip if data not available
                if snapshot.cftc_positioning > -threshold:  # Net short is negative
                    return False, f"CFTC net position {snapshot.cftc_positioning} not short enough"
            
            # Days to catalyst cluster
            elif condition_type == 'days_to_catalyst_cluster':
                min_days = condition.get('min_days', 0)
                max_days = condition.get('max_days', 30)
                # Find nearest catalyst
                days_to_catalyst = None
                for catalyst in self.config.catalysts:
                    cat_date_str = catalyst.get('date')
                    if cat_date_str:
                        cat_date = datetime.strptime(cat_date_str, '%Y-%m-%d').date()
                        current = snapshot.timestamp.date() if isinstance(snapshot.timestamp, datetime) else snapshot.timestamp
                        days = (cat_date - current).days
                        if days >= 0:
                            if days_to_catalyst is None or days < days_to_catalyst:
                                days_to_catalyst = days
                
                if days_to_catalyst is None:
                    return False, "No upcoming catalyst found"
                if days_to_catalyst < min_days or days_to_catalyst > max_days:
                    return False, f"Days to catalyst {days_to_catalyst} not in [{min_days}, {max_days}]"
            
            # Crack spread condition
            elif condition_type == 'crack_spread_above':
                threshold = condition.get('threshold', 15)
                region = condition.get('region', 'USGC')
                spread = snapshot.crack_spreads.get(region)
                if spread is None:
                    continue  # Skip if data not available
                if spread < threshold:
                    return False, f"Crack spread {spread:.2f} < {threshold}"
            
            # Days to earnings
            elif condition_type == 'days_to_earnings':
                min_days = condition.get('min_days', 0)
                max_days = condition.get('max_days', 30)
                days = snapshot.days_until_event('EARNINGS', self.config.underlying)
                if days is None:
                    return False, "No earnings date found"
                if days < min_days or days > max_days:
                    return False, f"Days to earnings {days} not in [{min_days}, {max_days}]"
            
            # IV rank condition
            elif condition_type == 'iv_rank_below':
                threshold = condition.get('threshold', 50)
                iv_rank = snapshot.get_iv_rank(self.config.underlying)
                if iv_rank is None:
                    continue  # Skip if data not available
                if iv_rank >= threshold:
                    return False, f"IV rank {iv_rank:.1f} >= {threshold}"
            
            # Stock price below threshold
            elif condition_type == 'stock_price_below':
                threshold = condition.get('threshold')
                if threshold:
                    price = snapshot.get_price(self.config.underlying)
                    if price and price >= threshold:
                        return False, f"Stock price {price:.2f} >= {threshold}"
            
            # Always condition (for hedges)
            elif condition_type == 'always':
                continue  # Always passes
            
            # Major bank beat condition (for KRE)
            elif condition_type == 'major_bank_beat':
                # Check if required earnings have happened and were positive
                tickers = condition.get('tickers', [])
                for ticker in tickers:
                    result = snapshot.earnings_results.get(ticker, {})
                    if not result.get('beat', False):
                        return False, f"{ticker} earnings not confirmed as beat"
            
            # Yield curve condition
            elif condition_type == 'yield_curve_normal':
                spread_threshold = condition.get('spread_10y_2y_above', 0)
                rate_10y = snapshot.rates.get('10Y', 0)
                rate_2y = snapshot.rates.get('2Y', 0)
                spread = rate_10y - rate_2y
                if spread < spread_threshold:
                    return False, f"10Y-2Y spread {spread*100:.0f}bps < {spread_threshold*100:.0f}bps"
            
            # Verification gate (for contingent strategies like MPC)
            # This is handled separately - skip here
            elif condition_type in ('vlo_earnings_positive', 'msft_meta_ai_capex_positive', 
                                    'stock_stable_post_tech_earnings', 'no_china_export_escalation',
                                    'no_fomc_hawkish_signal', 'defense_eo_signed', 'days_to_eo_deadline',
                                    'paired_with_ktos'):
                # These require external verification - default to pass if not implemented
                continue
        
        return True, None
    
    def _check_take_profit(
        self, 
        snapshot: MarketSnapshot, 
        underlying_price: Optional[float],
        pnl_pct: float,
        rules: Dict
    ) -> Optional[Signal]:
        """Check take-profit conditions."""
        
        condition = rules.get('condition', '')
        threshold = rules.get('threshold')
        action = rules.get('action', 'exit_all')
        
        triggered = False
        
        if condition == 'vix_above' and snapshot.vix_spot:
            if snapshot.vix_spot >= threshold:
                triggered = True
        
        elif condition == 'stock_price_above' and underlying_price:
            if underlying_price >= threshold:
                triggered = True
        
        elif condition == 'stock_price_pct_gain' and underlying_price:
            # Need entry price to calculate gain - use position tracking
            # For now, use P&L percentage as proxy
            if pnl_pct >= threshold:
                triggered = True
        
        elif condition == 'spread_value_above':
            # Need current spread value - check P&L
            if pnl_pct >= (threshold / 100) * 100:  # Rough approximation
                triggered = True
        
        if triggered:
            exit_pct = 0.5 if 'exit_50pct' in action else 1.0
            return Signal(
                signal_type=SignalType.EXIT_PARTIAL if exit_pct < 1.0 else SignalType.EXIT_FULL,
                strategy_name=self.name,
                underlying=self.config.underlying,
                timestamp=snapshot.timestamp,
                exit_reason=ExitReason.TAKE_PROFIT,
                exit_pct=exit_pct,
                urgency=4,
                notes=f"Take profit triggered: {condition} at {threshold}",
            )
        
        return None
    
    def _check_stop_loss(
        self,
        snapshot: MarketSnapshot,
        underlying_price: Optional[float],
        pnl_pct: float,
        rules: Dict
    ) -> Optional[Signal]:
        """Check stop-loss conditions."""
        
        condition = rules.get('condition', '')
        threshold = rules.get('threshold')
        
        triggered = False
        
        if condition == 'stock_drops_pct' and underlying_price:
            # This needs reference to entry price - use P&L as proxy
            if pnl_pct <= threshold:  # threshold is negative for losses
                triggered = True
        
        elif condition == 'sector_down_pct':
            # Would need sector index - simplify to underlying
            if pnl_pct <= threshold:
                triggered = True
        
        if triggered:
            return Signal(
                signal_type=SignalType.EXIT_FULL,
                strategy_name=self.name,
                underlying=self.config.underlying,
                timestamp=snapshot.timestamp,
                exit_reason=ExitReason.STOP_LOSS,
                urgency=5,  # Stops are urgent
                notes=f"Stop loss triggered: {condition} at {threshold}%",
            )
        
        return None
    
    def _check_time_stop(self, current_date: date, rules: Dict) -> Optional[Signal]:
        """Check time-based exit conditions."""
        
        # Check for specific date stop
        stop_date_str = rules.get('date')
        if stop_date_str:
            stop_date = datetime.strptime(stop_date_str, '%Y-%m-%d').date()
            if current_date >= stop_date:
                return Signal(
                    signal_type=SignalType.EXIT_FULL,
                    strategy_name=self.name,
                    underlying=self.config.underlying,
                    timestamp=datetime.combine(current_date, datetime.min.time()),
                    exit_reason=ExitReason.TIME_STOP,
                    urgency=3,
                    notes=f"Time stop reached: {stop_date}",
                )
        
        # Check for days_after_catalyst
        days_after = rules.get('days_after_catalyst')
        if days_after:
            # Find primary catalyst date
            primary_catalyst = self.config.get_primary_catalyst()
            if primary_catalyst:
                cat_date_str = primary_catalyst.get('date')
                if cat_date_str:
                    cat_date = datetime.strptime(cat_date_str, '%Y-%m-%d').date()
                    if current_date >= cat_date + timedelta(days=days_after):
                        return Signal(
                            signal_type=SignalType.EXIT_FULL,
                            strategy_name=self.name,
                            underlying=self.config.underlying,
                            timestamp=datetime.combine(current_date, datetime.min.time()),
                            exit_reason=ExitReason.TIME_STOP,
                            urgency=3,
                            notes=f"Time stop: {days_after} days after catalyst",
                        )
        
        return None
    
    def _check_thesis_invalidation(
        self, 
        snapshot: MarketSnapshot, 
        invalidations: List[Dict]
    ) -> Optional[Signal]:
        """Check thesis invalidation conditions."""
        
        for inv in invalidations:
            condition = inv.get('condition', '')
            threshold = inv.get('threshold')
            
            if condition == 'crack_spread_below':
                spread = snapshot.crack_spreads.get('USGC')
                if spread and spread < threshold:
                    return Signal(
                        signal_type=SignalType.EXIT_FULL,
                        strategy_name=self.name,
                        underlying=self.config.underlying,
                        timestamp=snapshot.timestamp,
                        exit_reason=ExitReason.THESIS_INVALIDATION,
                        urgency=4,
                        notes=f"Thesis invalidated: crack spread {spread:.2f} < {threshold}",
                    )
            
            elif condition == 'yield_move_bps_week':
                # Would need rate history - skip for now
                pass
            
            elif condition == 'government_shutdown_days':
                # Would need to track shutdown status
                pass
        
        return None
    
    def _check_kill_switch(self, snapshot: MarketSnapshot, rules: Dict) -> Optional[Signal]:
        """Check kill switch (emergency exit) conditions."""
        
        condition = rules.get('condition', '')
        threshold = rules.get('threshold')
        
        if condition == 'vix_below_sustained':
            # For simplicity, just check current VIX
            if snapshot.vix_spot and snapshot.vix_spot < threshold:
                return Signal(
                    signal_type=SignalType.EXIT_FULL,
                    strategy_name=self.name,
                    underlying=self.config.underlying,
                    timestamp=snapshot.timestamp,
                    exit_reason=ExitReason.KILL_SWITCH,
                    urgency=5,
                    notes=f"Kill switch: VIX {snapshot.vix_spot:.2f} < {threshold}",
                )
        
        return None


class SingleOptionStrategy(BaseStrategy):
    """
    Strategy for single-leg option positions (protective puts, etc.).
    """
    
    def check_entry(self, snapshot: MarketSnapshot) -> Optional[Signal]:
        """Evaluate entry for single option position."""
        
        if self._entry_signal_generated:
            return None
        
        if not self.config.enabled:
            return None
        
        current_date = snapshot.timestamp.date() if isinstance(snapshot.timestamp, datetime) else snapshot.timestamp
        if not self.is_in_entry_window(current_date):
            return None
        
        # For hedges like SPY_PROTECTIVE_PUT, entry is usually immediate
        for condition in self.config.entry_conditions:
            if condition.get('condition') == 'always':
                self._entry_signal_generated = True
                
                structure = self.get_target_structure(snapshot)
                
                return Signal(
                    signal_type=SignalType.ENTRY,
                    strategy_name=self.name,
                    underlying=self.config.underlying,
                    timestamp=snapshot.timestamp,
                    target_structure=structure,
                    urgency=3,
                    notes=f"Hedge entry: {self.name}",
                )
        
        return None
    
    def check_exit(
        self, 
        snapshot: MarketSnapshot, 
        position: Any,
        position_pnl_pct: float
    ) -> Optional[Signal]:
        """Check exit conditions for single option."""
        
        exit_rules = self.config.exit_rules
        
        # Check monetize condition (for protective puts)
        monetize = exit_rules.get('monetize', {})
        if monetize:
            condition = monetize.get('condition', '')
            threshold = monetize.get('threshold')
            
            if condition == 'spy_down_pct':
                # Check if SPY has dropped significantly
                spy_price = snapshot.get_price('SPY')
                # Would need entry price tracking - use P&L as proxy
                if position_pnl_pct >= 50:  # Put is profitable, SPY must be down
                    return Signal(
                        signal_type=SignalType.EXIT_PARTIAL,
                        strategy_name=self.name,
                        underlying=self.config.underlying,
                        timestamp=snapshot.timestamp,
                        exit_reason=ExitReason.TAKE_PROFIT,
                        exit_pct=0.5,
                        urgency=3,
                        notes="Monetizing protective put gain",
                    )
        
        return None
    
    def get_target_structure(self, snapshot: MarketSnapshot) -> Dict[str, Any]:
        """Build target structure for single option."""
        
        current_date = snapshot.timestamp.date() if isinstance(snapshot.timestamp, datetime) else snapshot.timestamp
        target_expiration = current_date + timedelta(days=self.config.expiration_target_dte)
        
        # Adjust to Friday
        days_until_friday = (4 - target_expiration.weekday()) % 7
        if days_until_friday == 0 and target_expiration.weekday() != 4:
            days_until_friday = 7
        target_expiration = target_expiration + timedelta(days=days_until_friday)
        
        # Calculate strike based on OTM percentage
        underlying_price = snapshot.get_price(self.config.underlying)
        strike = self.config.long_strike
        
        if strike is None and underlying_price:
            # Calculate OTM strike
            legs = self.config.raw_config.get('structure', {}).get('legs', {})
            long_leg = legs.get('long', {})
            otm_pct = long_leg.get('strike_otm_pct', 5)
            
            # For puts, OTM means below current price
            if self.config.right == 'P':
                strike = underlying_price * (1 - otm_pct / 100)
            else:
                strike = underlying_price * (1 + otm_pct / 100)
            
            # Round to standard strike
            strike = round(strike / 5) * 5
        
        return {
            'structure_type': self.config.structure_type,
            'underlying': self.config.underlying,
            'expiration': target_expiration,
            'strike': strike,
            'right': self.config.right,
            'quantity': 1,
        }


def create_strategy(config: StrategyConfig) -> BaseStrategy:
    """
    Factory function to create the appropriate strategy type.
    
    Args:
        config: StrategyConfig for the strategy
        
    Returns:
        Appropriate BaseStrategy subclass instance
    """
    structure_type = config.structure_type.lower()
    
    if 'spread' in structure_type:
        return VerticalSpreadStrategy(config)
    elif structure_type in ('long_put', 'long_call'):
        return SingleOptionStrategy(config)
    else:
        # Default to vertical spread
        return VerticalSpreadStrategy(config)


# =============================================================================
# MODULE TESTING
# =============================================================================

if __name__ == "__main__":
    print("Strategy Base Module")
    print("=" * 60)
    
    # Test StrategyConfig parsing
    test_config = {
        'enabled': True,
        'tier': 'A',
        'conviction_score': 78,
        'theme': 'refiner_venezuela',
        'underlying': 'VLO',
        'structure': {
            'type': 'debit_call_spread',
            'expiration_target_dte': 30,
            'legs': {
                'long': {'right': 'C', 'strike_selection': 'fixed', 'strike_value': 180},
                'short': {'right': 'C', 'strike_selection': 'fixed', 'strike_value': 195},
            }
        },
        'entry_window': {
            'start': '2026-01-27',
            'end': '2026-01-28',
        },
        'entry_conditions': [
            {'condition': 'crack_spread_above', 'threshold': 17},
        ],
        'position_sizing': {
            'conservative': 250,
            'base': 400,
            'aggressive': 500,
        }
    }
    
    config = StrategyConfig.from_yaml('VLO_EARNINGS_CALL_SPREAD', test_config)
    print(f"\nParsed config: {config.name}")
    print(f"  Underlying: {config.underlying}")
    print(f"  Strikes: {config.long_strike}/{config.short_strike}")
    print(f"  Entry window: {config.entry_start} to {config.entry_end}")
    print(f"  Base sizing: ${config.sizing_base}")
    
    # Create strategy
    strategy = create_strategy(config)
    print(f"\nCreated strategy: {strategy}")
